package functionParser;

interface ParsingProblemType{

int TOO_MANY_RIGHT_BRACKETS = 0;
int TOO_MANY_LEFT_BRACKETS  = 1;
int RIGHT_BRACKET_UNMATCHED = 2;
int TOO_MANY_RIGHT_PARENTHESES  = 3;
int TOO_MANY_LEFT_PARENTHESES   = 4;
int RIGHT_PARENTHESES_UNMATCHED = 5;
int UNRECOGNIZED_VARIABLE = 6;
int UNRECOGNIZED_FUNCTION = 7;

}