nds: libglu1-mesa (= 8.0.4-0ubuntu0.2), libgl1-mesa-dev | libgl-dev
Conflicts: mesa-glide2-dev (<< 5.0.0-1), mesag-dev (<< 5.0.0-1), mesag3+ggi-dev (<< 5.0.0-1), xlibmesa-dev
Description: Mesa OpenGL utility library -- development files
 Includes headers and static libraries for compiling programs with GLU.
 .
 For a complete description of GLU, please look at the libglu1-mesa
 package.
Homepage: http://mesa3d.sourceforge.net/
Original-Maintainer: Debian X Strike Force <debian-x@lists.debian.org>

Package: ubuntu-artwork
Status: install ok installed
Priority: optional
Section: 